extends: airbnb-base
parser: babel-eslint

env:
  node: true
  es6: true

globals:
  artifacts: true

rules:
  no-use-before-define: 0
  class-methods-use-this: 0
  no-underscore-dangle: 0
  max-len:
    - error
    - 100
