extends:
  - airbnb-base
  - eslint:recommended

parser: babel-eslint

env:
  node: true
  es6: true

globals:
  artifacts: true

rules:
  no-use-before-define: 0
  class-methods-use-this: 0
  no-underscore-dangle: 0
  no-undef: off
  import/no-unresolved: off
  prefer-destructuring: off
  no-console: off
  max-line-length: 200
  camelcase: off
  no-await-in-loop: off
  max-len:
    - error
    - 150
