extends: airbnb-base
parser: babel-eslint
plugins:
  - babel
  - mocha
env:
  node: true
  es6: true
  mocha: true
globals:
  web3: true
  artifacts: true
  contract: true
rules:
  no-use-before-define: 0
  class-methods-use-this: 0
  no-underscore-dangle: 0
  import/prefer-default-export: 0
  mocha/no-exclusive-tests: error
  max-len:
    - error
    - 100
